### ISSUE TITLE
Invalid Base32 characters

### ISSUE THREAD

**Issue by JAICHANGPARK** [Daegalus/dart-otp#22]
I had some problem about using android device in flutter 

>The following FormatException was thrown building Builder:
Invalid Base32 characters

Can I use this package on flutter ?

**Comment by Daegalus** [comment]
Yes, it works fine in flutter. It means your Secret has invalid character for the Base32 format. Check your secret.

**Comment by JAICHANGPARK** [comment]
@Daegalus  Thank you sir!
I solved this problem to fix my secret code 👍
