### ISSUE TITLE
when i added otp plug to my app.

### ISSUE THREAD

**Issue by muhammednazil** [Daegalus/dart-otp#25]
/Users/qlinksoftware/Documents/FlutterSdk/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in my-table-flutter-master...         

The current Dart SDK version is 2.10.4.

    Because test >=1.16.0-nullsafety <1.16.0-nullsafety.5 requires SDK version >=2.10.0-0 <2.10.0 and test >=1.16.0-nullsafety.5 <1.16.0-nullsafety.8 depends on pedantic >=1.10.0-nullsafety <1.10.0, test >=1.16.0-nullsafety <1.16.0-nullsafety.8 requires pedantic >=1.10.0-nullsafety <1.10.0.
    And because test >=1.16.0-nullsafety.8 requires SDK version >=2.12.0-0 <3.0.0 and test >=0.12.0-beta.3 <1.3.0 requires SDK version >=1.8.0 <2.0.0-∞, test >=0.12.0-beta.3 <1.3.0-∞ or >=1.16.0-nullsafety requires pedantic >=1.10.0-nullsafety <1.10.0.
    And because test >=1.3.0 <1.12.0 depends on boolean_selector ^1.0.0 and test >=1.12.0 <1.13.0 depends on test_api 0.2.14, test >=0.12.0-beta.3 <1.13.0-∞ or >=1.16.0-nullsafety requires pedantic >=1.10.0-nullsafety <1.10.0 or boolean_selector ^1.0.0 or test_api 0.2.14.
    And because test >=1.13.0 <1.14.5 depends on test_api 0.2.15 and test >=1.14.5 <1.15.0 depends on test_api 0.2.16, test >=0.12.0-beta.3 <1.15.0-∞ or >=1.16.0-nullsafety requires pedantic >=1.10.0-nullsafety <1.10.0 or boolean_selector ^1.0.0 or test_api 0.2.14 or 0.2.15 or 0.2.16.
    And because test >=1.15.0 <1.15.3 depends on test_api 0.2.17 and test >=1.15.3 <1.15.5 depends on test_api 0.2.18, test >=0.12.0-beta.3 <1.15.5-∞ or >=1.16.0-nullsafety requires pedantic >=1.10.0-nullsafety <1.10.0 or boolean_selector ^1.0.0 or test_api 0.2.14 or 0.2.15 or 0.2.16 or 0.2.17 or 0.2.18.
    And because test >=1.15.5 <1.16.0-nullsafety depends on test_api 0.2.18+1 and every version of flutter_test from sdk depends on boolean_selector 2.1.0-nullsafety.1, if test >=0.12.0-beta.3 and flutter_test any from sdk then test_api 0.2.14 or 0.2.15 or 0.2.16 or 0.2.17 or 0.2.18 or 0.2.18+1 or pedantic >=1.10.0-nullsafety <1.10.0.
(1) So, because every version of flutter_test from sdk depends on test_api 0.2.19-nullsafety.2 and every version of no_bloc depends on test ^1.0.0, if flutter_test any from sdk and no_bloc any then pedantic >=1.10.0-nullsafety <1.10.0.

    Because quick_log >=1.1.0 <1.1.1 depends on no_bloc ^0.2.3 and quick_log >=1.0.0 <1.1.0 depends on no_bloc ^0.2.0, quick_log >=1.0.0 <1.1.1 requires no_bloc ^0.2.0.
    And because quick_log ^1.1.1 depends on no_bloc >=0.3.4 <2.0.0, quick_log ^1.0.0 requires no_bloc ^0.2.0 or >=0.3.4 <2.0.0.
    And because if flutter_test any from sdk and no_bloc any then pedantic >=1.10.0-nullsafety <1.10.0 (1), if flutter_test any from sdk and quick_log ^1.0.0 then pedantic >=1.10.0-nullsafety <1.10.0.
(2) So, because otp >=2.2.2 depends on quick_log ^1.0.0 and syncfusion_flutter_core >=18.2.54 depends on pedantic >=1.9.0 <1.9.9, one of flutter_test any from sdk or otp >=2.2.2 or syncfusion_flutter_core >=18.2.54 must be false.

    Because no versions of syncfusion_flutter_datepicker match >18.3.44-beta <18.3.47-beta and syncfusion_flutter_datepicker >=18.3.47-beta <18.3.48-beta depends on syncfusion_flutter_core ^18.3.47, syncfusion_flutter_datepicker >18.3.44-beta <18.3.48-beta requires syncfusion_flutter_core ^18.3.47.
    And because syncfusion_flutter_datepicker >=18.3.48-beta <18.3.50-beta depends on syncfusion_flutter_core ^18.3.48 and syncfusion_flutter_datepicker >=18.3.50-beta <18.3.51-beta depends on syncfusion_flutter_core ^18.3.50, syncfusion_flutter_datepicker >18.3.44-beta <18.3.51-beta requires syncfusion_flutter_core ^18.3.47.
    And because syncfusion_flutter_datepicker >=18.3.51-beta depends on syncfusion_flutter_core ^18.3.51 and syncfusion_flutter_datepicker 18.3.44-beta depends on syncfusion_flutter_core ^18.3.44, syncfusion_flutter_datepicker >=18.3.44-beta requires syncfusion_flutter_core ^18.3.44.
    And because one of flutter_test any from sdk or otp >=2.2.2 or syncfusion_flutter_core >=18.2.54 must be false (2), one of flutter_test any from sdk or otp >=2.2.2 or syncfusion_flutter_datepicker >=18.3.44-beta must be false.
    And because mytableqatar depends on syncfusion_flutter_datepicker ^18.3.44-beta, flutter_test from sdk is incompatible with otp >=2.2.2.
    So, because mytableqatar depends on both otp ^2.2.3 and flutter_test any from sdk, version solving failed.
pub get failed (1;     So, because mytableqatar depends on both otp ^2.2.3 and flutter_test any from sdk, version solving failed.)
Process finished with exit code 1

**Comment by Daegalus** [comment]
This package hasn't been updated for null safety, so you can't use it with nullsafety packages. I'm still working on it. The solution is to not use nullsafety versions

**Comment by muhammednazil** [comment]
Thank you.

**Comment by muhammednazil** [comment]
Thank you
