### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by timosturm** [Daegalus/dart-otp#27]
The readme [here](https://pub.dev/packages/otp), [here](https://daegalus.github.io/dart-otp/api/) and [here](https://github.com/Daegalus/dart-otp) state the following:
```
OTP.generateTOTPCode(String secret, int currentTime, {int length: 6, int interval: 30, Algorithm algorithm: Algorithm.SHA1, bool isGoogle: true}) 
```
and
```
OTP.generateTOTPCodeString(String secret, int currentTime, {int length: 6, int interval: 30, Algorithm algorithm: Algorithm.SHA1, bool isGoogle: true})
```
The default value for `isGoogle` is supposed to be `true` but in the code, it is actually set to `false`.
See:
https://github.com/Daegalus/dart-otp/blob/9617cce0bf8268c93826f88eac24733808376370/lib/otp.dart#L22

and 

https://github.com/Daegalus/dart-otp/blob/9617cce0bf8268c93826f88eac24733808376370/lib/otp.dart#L36

I do not know which is the intended value, so I just leave this here.

**Comment by Daegalus** [comment]
Thank you for this. The code is the correct one so I will update the readme soon.

**Comment by Daegalus** [comment]
Fixed in latest commit.
