### ISSUE TITLE
Publish version 3.0.0-nullsafety.0

### ISSUE THREAD

**Issue by feinstein** [Daegalus/dart-otp#28]
Version `3.0.0-nullsafety.0` wasn't published on pub, could you publish it please? I am getting constrain issues for the logging library that was removed.

**Comment by Daegalus** [comment]
My apologies, I thought I had. I will do so shortly.

**Comment by Daegalus** [comment]
Done, https://pub.dev/packages/otp/versions/3.0.0-nullsafety.0 sorry for the delay

**Comment by feinstein** [comment]
Not a problem, many thanks!
