### ISSUE TITLE
Error in readme and documentation

### ISSUE THREAD

**Issue by kirillmokretsov** [Daegalus/dart-otp#30]
In [readme](../blob/master/README.md) and [code's comment](../blob/master/lib/otp.dart) it is

> OTP.generateTOTPCode(String secret, int currentTime, {int length: 6, int interval: 30, Algorithm algorithm: Algorithm.SHA1, bool isGoogle: false})

> OTP.generateTOTPCodeString(String secret, int currentTime, {int length: 6, int interval: 30, Algorithm algorithm: Algorithm.SHA1, bool isGoogle: false})

> /// Optional parameters to change the length of the code provided (default 6), interval (default 30), and hashing algorithm (default SHA1)
> /// These settings are defaulted to the RFC standard but can be changed.

But actually it is SHA256:

``` dart
  static int generateTOTPCode(String secret, int time,
    {int length = 6, int interval = 30, Algorithm algorithm = Algorithm.SHA256, bool isGoogle = false}) {
```

``` dart
  static int generateTOTPCodeString(String secret, int time,
    {int length = 6, int interval = 30, Algorithm algorithm = Algorithm.SHA256, bool isGoogle = false}) {
```

**Comment by Daegalus** [comment]
My apologies, I'll fix the readme shortly.

**Comment by Daegalus** [comment]
Updated the docs, and pushed up 3.0.0 as it has been nullsafe for a while. Thanks for catching that.
