### ISSUE TITLE
Does this lib work?

### ISSUE THREAD

**Issue by blelump** [Daegalus/dart-otp#31]
Hi,

We've spent quite some time today looking around to find potential issue with the input we've provided to `generateTOTPCodeString` but eventually failed. All the test passes, but seems that the generated codes do not match. We did the comparison against https://github.com/bellstrand/totp-generator/blob/master/test/index.spec.js#L6 .

**Comment by Daegalus** [comment]
It should, give me some time to run some tests and see what I find.At a quick glance at their code, it could be the algorithm. They default to SHA1, and I default to SHA256 to be more compatible with Google Authenticator and most modern authenticator apps that default to SHA256. Maybe try setting the NodeJS one to SHA256, or this one to SHA1 when you make the call?

Other than that, I will do some digging.

**Comment by blelump** [comment]
Thanks for reply.

Tried to mimic test https://github.com/bellstrand/totp-generator/blob/master/test/index.spec.js#L31 so having:
```
    test(
        '',
        () {
      final code = OTP.generateTOTPCode('JBSWY3DPEHPK3PXP', 1465324707000, algorithm: Algorithm.SHA1, interval: 60);
      expect(code, equals(345785));
    });
```
it gets:
```
  Expected: <345785>
    Actual: <34108>
```

**Comment by Daegalus** [comment]
Ok, for your first example, pass in `isGoogle: true` the reason being is Google pads the secret to the right length by copying the secret over and over until all the spots in the array are taken. the RFC spec pads with 0s. Most OTP libraries default to Google's padding, while others don't. To support both, I added this flag. When I take your first non-working example and use `isGoogle: true` it matches.

I also encourage using `OTP.generateTOTPCodeString()` as then you wont lose leading 0s that get removed when keeping it as an integer. unless you want to keep it an integer.

As for your second example, setting isGoogle didnt make it work, so I am not sure if its my library or theirs that isn't doing something right.

**Comment by Daegalus** [comment]
Looks like its something with the way they use the DateTime.parse() function. If i take that same time as milliseconds `1546300800000` and enter it into my function, i get the right code.

```dart
final code6 = OTP.generateTOTPCodeString(
      'JBSWY3DPEHPK3PXP', 1465324707000,
      interval: 60, algorithm: Algorithm.SHA1, isGoogle: true);
  print(code6);

  final code7 = OTP.generateTOTPCodeString('J22U6B3WIWRRBTAV', 1546300800000, algorithm: Algorithm.SHA1, interval: 30, isGoogle: true);
  print(code7);```

```sh
~/workspace/dart-otp/example on   master !1 ?1                                             at  14:58:38
❯ dart example.dart
313995
793957```

This is my nodejs code for testing the same, using 2 different libraries.:

```js
const totp = require("totp-generator");
const OTPAuth = require("otpauth");

global.Date.now = () => { return 1546300800000; };
// Keys provided must be base32 strings, ie. only containing characters matching (A-Z, 2-7, =).
const token = totp("J22U6B3WIWRRBTAV", {algorithm: "SHA-1", period: 30});

console.log("TOTP-Generator: " + token); // prints a 6-digit time-based token based on provided key and current time

// Create a new TOTP object.
let otp = new OTPAuth.TOTP({
    issuer: 'ACME',
    label: 'AzureDiamond',
    algorithm: 'SHA1',
    digits: 6,
    period: 30,
    secret: 'J22U6B3WIWRRBTAV' // or "OTPAuth.Secret.fromBase32('NB2W45DFOIZA')"
});

// Generate a token.
let token2 = otp.generate();

console.log("OTPAuth: " + token2)
```

```sh
~/workspace/totpjs                                                                           at  14:58:40
❯ node index.js
TOTP-Generator: 793957
OTPAuth: 793957
```

**Comment by Daegalus** [comment]
Ya, the datetime.parse is off. 

```dart
print(DateTime.parse('2019-01-01 00:00:00.000').millisecondsSinceEpoch);
```

results in `1546329600000` which is not the same as `1546300800000` and I think its because that library isn't setting the timezone (or UTC) correctly.

```dart
print(DateTime.parse('2019-01-01 00:00:00.000 Z').millisecondsSinceEpoch);
```

this results in the proper `1546300800000`, just needs that `Z` in the time string.

**Comment by Daegalus** [comment]
Closing this for now, if you are still having issues, please reopen and we can go from there.
