### ISSUE TITLE
Unable to create otp for Instagram two factor authenticator.

### ISSUE THREAD

**Issue by dinesh-utrade** [Daegalus/dart-otp#34]
Hi 
The TOTP created for Instagram two factor authentication is not valid. I also checked with google authenticator which is working perfectly.  I have used all algorithm provided by the library.
Please look into the issue

**Comment by Daegalus** [comment]
Can you provide a bit more information, whats the code you used? If possible provide a secret that I can use to compare. I can't reproduce the error.

**Comment by stevenBang** [comment]
google account give me this scert code
"k5aj dq34 r4cc ifps b53t yl32 7tix k4q5"
it's work on google app.
but this function is not work.

**Comment by Daegalus** [comment]
Try removing all the spaces, they are invalid characters for BASE32. You might have to capitalize all letters too.

**Comment by dinesh-utrade** [comment]
Hey Yulian Kuncheff
I have tried all the ways you have mentioned in your mail. It is still not
working.

Regards
Dinesh Kumar

**Comment by Daegalus** [comment]
Ok, have you tried setting `isGoogle` to true and the `algorithm` to SHA1, or any combination of those settings?

**Comment by dinesh-utrade** [comment]
Yeah, I have tried isGoogle to true and all algorithms provided by the
plugin.

**Comment by Daegalus** [comment]
Are you handling timezones correctly?

```
  tz.initializeTimeZones();
  final la = tz.getLocation('America/Los_Angeles');
  final code8 = OTP.generateTOTPCodeString('***',
      tz.TZDateTime.now(la).millisecondsSinceEpoch,
      isGoogle: true, algorithm: Algorithm.SHA1);
```

This worked for me for instagram. I removed all spaces from the secret key, but then used those settings to make it work. I used the `timezone` library to handle timezones. DateTime.now().millisecondsSinceEpoch is default UTC.

**Comment by dinesh-utrade** [comment]
Thanks Yulian Kuncheff,
The issue was not due to Timezone. Actually I was converting the secret key
in base32 before passing it to the plugin. Instagram secret is already
base32 string after removing all the spaces.

Regards
Dinesh Kumar

**Comment by Daegalus** [comment]
Very glad to hear you got it working, sorry for not helping sooner. Appreciate that you reported back with your findings. I'll add it to my list of things to check and improve documentation.
