### ISSUE TITLE
HOTP tokens are not same with Google Authenticator tokens

### ISSUE THREAD

**Issue by burcus** [Daegalus/dart-otp#43]
I'm trying to implement hotp generate function to my app (for totp it works well). And I'm using[ this site](https://stefansundin.github.io/2fa-qr/) to test my tokens. For this secret: NBQWQYLIEBXWMIDZMFQSAOSE and counter = 0 values, Google Authenticator generates: "253 778" test token. But `OTP.generateHOTPCodeString("NBQWQYLIEBXWMIDZMFQSAOSE", 0, algorithm: Algorithm.SHA1) `function generates "392731" token.
What could be the problem causing this issue?

**Comment by burcus** [comment]
There is no isGoogle parameter for generateHOTPCode/String functions. But this issue solved when secretList generated by using base32.decode(). 
```
if (isGoogle) {
      secretList = base32.decode(secret);
    }
```
So when isGoogle is true, it creates same tokens with Google Authenticator. Maybe adding isGoogle parameter to this function in the package can fix this issue @Daegalus

**Comment by Daegalus** [comment]
This is closed, but did you still want this feature? I have no problem adding it. The reason I never did was because I didn't think Google even had a HOTP option.

Let me know.

**Comment by burcus** [comment]
@Daegalus Hi, thanks for feedback. I closed it cause I found cause of the issue. Google auth has counter based tokens. How long does it take to add it?

**Comment by Daegalus** [comment]
Shouldn't be too long. I can do it at this moment, but later tonight when I have free time, I can probably get something out in a half an hour, probably less. I just need to add it as an optional parameter to the HOTP functions, similarly to the TOTP functions. By making it optional, I shouldn't break anyone using it as is currently.

I will reopen this ticket so I can track it and close it once I am done. If I don't get to it tonight, I can definitely get to it tomorrow.

**Comment by burcus** [comment]
Yes, this will probably take only 5 minutes of your time 😅. I hope you add that tonight. Thanks.

**Comment by Daegalus** [comment]
v3.1.2 should have your fix, let me know if it doesn't work for you.

**Comment by burcus** [comment]
@Daegalus Now I check your changes, but it seems uneffective.
```
  if (isGoogle) {
      secretList = base32.decode(secret);
   }

``` 
after these lines there is condition as below:

```
 if ((!isGoogle && (!isHOTP || useTOTPPaddingForHOTP)) ||
        (isHOTP && isGoogle)) {
      secretList = _padSecret(secretList, secretbytes);
    } else if (isHOTP && !isGoogle) {
      _showHOTPWarning(mac);
    }

```
In if conditions there is ` || (isHOTP && isGoogle`  condition. This invalidates the secretList assignment above. Cause if parameters are isHOTP = true, is Google = true, it'll return true value, Therefore secretList will be _padSecret result instead of base32.decode(secret).  But if isGoogle is true, secretList should be base32.decode(secret) result.

**Comment by Daegalus** [comment]
> @Daegalus I checked your changes, but it seems uneffective.
> 
> ```
>   if (isGoogle) {
>       secretList = base32.decode(secret);
>    }
> ```
> 
> after these lines there is condition as below:
> 
> ```
>  if ((!isGoogle && (!isHOTP || useTOTPPaddingForHOTP)) ||
>         (isHOTP && isGoogle)) {
>       secretList = _padSecret(secretList, secretbytes);
>     } else if (isHOTP && !isGoogle) {
>       _showHOTPWarning(mac);
>     }
> ```
> 
> In if conditions there is ` || (isHOTP && isGoogle` condition. This invalidates the secretList assignment above. Cause if parameters are isHOTP = true, is Google = true, it'll return true value, Therefore secretList will be _padSecret result instead of base32.decode(secret). But if isGoogle is true, secretList should be base32.decode(secret) result.

It shouldn't be ineffectual. Because if you notice padSecret's parameters include `secretList`

So it will base32.decode it, then pad it with secret bytes, but I guess you don't need to pad it, and I already provided a parameter to use TOTP padding for HOTP. Anyways, Ill remove the new condition. sorry about that, got myself confused with the `useTOTPforHOTP` flag i have.

Anyeays, v3.1.3 is released, try that.

**Comment by burcus** [comment]
I didn't review your code deeply so i haven't comprehensive knowledge about your flags. 
But as you said, yes I don't need padding it. To clarify my situtation and help you, I want to give you a scenerio to produce it. 

Here is Google Authenticator outputs for some counter and secret key:
0: 253778, 1: 031481, 2: 57743, 3: 402264, ... and the secret key is NBQWQYLIEBXWMIDZMFQSAOSE.

With your latest changes:
```
    print(OTP.generateHOTPCodeString("NBQWQYLIEBXWMIDZMFQSAOSE", 0, isGoogle: true));
    print(OTP.generateHOTPCodeString("NBQWQYLIEBXWMIDZMFQSAOSE", 1, isGoogle: true));
    print(OTP.generateHOTPCodeString("NBQWQYLIEBXWMIDZMFQSAOSE", 2, isGoogle: true));
    print(OTP.generateHOTPCodeString("NBQWQYLIEBXWMIDZMFQSAOSE", 3, isGoogle: true));
```

output is:
```
flutter: 336006
flutter: 749446
flutter: 274441
flutter: 372014
```

But let's change a part of your code like this: (just a dummy change to show issue) 
```
....
  if ((!isGoogle && (!isHOTP || useTOTPPaddingForHOTP)) ||
        (isHOTP && !isGoogle)) {
      secretList = _padSecret(secretList, secretbytes);
    } else if (isHOTP && !isGoogle) {
      _showHOTPWarning(mac);
    }
```
Now the output is:
```
flutter: 253778
flutter: 031481
flutter: 577432
flutter: 402264
```
So it shouldn't be run _padSecret line to be same with Google Auth tokens. 
I hope I could clarify and I hope this help you. 😊

**Comment by burcus** [comment]
@Daegalus In v3.1.3 fixed this issue. Thanks.
