### ISSUE TITLE
404: http://daegalus.github.io/annotated/dart-otp/otp/otp.html

### ISSUE THREAD

**Issue by n8crwlr** [Daegalus/dart-otp#9]
FYI:

> Features:
> Generate TOTP and HOTP codes.
> **Annotated source code**

gives

![image](https://user-images.githubusercontent.com/54250425/63302899-9c296e80-c2de-11e9-8681-60691a6de9e7.png)

**Comment by Daegalus** [comment]
Sorry about that. I will fix it soon. Currently on vacation.

**Comment by Daegalus** [comment]
Fixed the docs, and updated it. Hope that helps.
